### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by lfoppiano** [allenai/scispacy#137] opened 2019-07-23 05:02 UTC
I've created the conda env, and ran `pip install scispacy` see the result: 

 
```
(scispacy) lucas-mbp:jats lfoppiano$ pip install scispacy
Collecting scispacy
  Using cached https://files.pythonhosted.org/packages/72/55/30b30a78abafaaf34d0d8368a090cf713964d6c97c5e912fb2016efadab0/scispacy-0.2.2-py3-none-any.whl
Collecting numpy (from scispacy)
  Downloading https://files.pythonhosted.org/packages/0f/c9/3526a357b6c35e5529158fbcfac1bb3adc8827e8809a6d254019d326d1cc/numpy-1.16.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
     |████████████████████████████████| 13.9MB 3.5MB/s 
Collecting joblib (from scispacy)
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
Collecting spacy>=2.1.3 (from scispacy)
  Downloading https://files.pythonhosted.org/packages/cb/ef/cccdeb1ababb2cb04ae464098183bcd300b8f7e4979ce309669de8a56b9d/spacy-2.1.6-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (34.6MB)
     |████████████████████████████████| 34.6MB 33.6MB/s 
Collecting conllu (from scispacy)
  Downloading https://files.pythonhosted.org/packages/ae/54/b0ae1199f3d01666821b028cd967f7c0ac527ab162af433d3da69242cea2/conllu-1.3.1-py2.py3-none-any.whl
Collecting awscli (from scispacy)
  Using cached https://files.pythonhosted.org/packages/e6/48/8c5ac563a88239d128aa3fb67415211c19bd653fab01c7f11cecf015c343/awscli-1.16.203-py2.py3-none-any.whl
Collecting nmslib>=1.7.3.6 (from scispacy)
  Using cached https://files.pythonhosted.org/packages/b2/4d/4d110e53ff932d7a1ed9c2f23fe8794367087c29026bf9d4b4d1e27eda09/nmslib-1.8.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Download error on https://pypi.org/simple/numpy/: [Errno 8] nodename nor servname provided, or not known -- Some packages may not be found!
    Couldn't find index page for 'numpy' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno 8] nodename nor servname provided, or not known -- Some packages may not be found!
    No local packages or working download links found for numpy
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mk/scd8428n18jfgh3jdthbvpz00000gn/T/pip-install-l00jm4xn/nmslib/setup.py", line 172, in <module>
        zip_safe=False,
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/anaconda3/envs/scispacy/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy')
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mk/scd8428n18jfgh3jdthbvpz00000gn/T/pip-install-l00jm4xn/nmslib/
(scispacy) lucas-mbp:jats lfoppiano$ 
```

To solve the issue I had to install `numpy` and `nmslib`: 

```
conda install numpy
conda install -c akode nmslib
```

It seems to work, but maybe is not the proper way to solve it - the pip script should be updated perhaps?

**Comment by DeNeutoy** [comment] 2019-07-23 13:34
Thanks! I think nmslib is a bit tricky to install as it is a python wrapper to a C++ library. It seems like the order of installation here might have caused this problem. It's a bit tricky to test stuff like this because i'm fairly certain it is system specific. I'll leave this open and see if other people have had the same issue.

If you're interested in testing it, you could try adding numpy to the requirements file at the top, cloning the repo and running `python setup.py install` in a clean conda environment. If that works for you, i'll definitely add numpy.

**Comment by lfoppiano** [comment] 2019-07-24 04:32
I've tested and indeed it requires numpy as dependency on top in the `setup.py` would avoid failing the installation, however I got stuck on the following point: 

```
nmslib.cc:16:10: fatal error: 'pybind11/pybind11.h' file not found
  #include <pybind11/pybind11.h>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
```

Which I"m not sure how to solve... cause `pybind11` is installed but the error persist. Looks more a problem of my system (however others might get as well).

**Comment by DeNeutoy** [comment] 2019-07-24 21:39
Hmm, thanks for testing that.

This issue might help with the pybind11 thing. If this gets to be a big problem many people run into, i'll make nmslib optional, as it's only used for the linker which not everyone will use. FYI from the next release, you should just be able to pip install only the models and just use spacy to load them, without having to even install scispacy. Perhaps that would suit you?

https://github.com/nmslib/nmslib/issues/307

**Comment by lfoppiano** [comment] 2019-07-25 06:16
@DeNeutoy  no problem. 
I reported the issue because I though this problem might impact more people. 

Actually I was looking into scispacy because I'm looking to a more robust sentence splitter working with scientific articles (e.g. ref and other noise usually result in wrong sentence segmentation).  This doesn't seems to be the case.

**Comment by DeNeutoy** [comment] 2019-07-25 06:36
Oh dear, sorry about that - would you might posting a small selection of failure cases?

**Comment by lfoppiano** [comment] 2019-07-26 05:19
ah don't worry... that's currently happening with any sentence segmenter actually... 
I can try to provide some failure cases, however I think the need is more radical... like having a completely different dataset than newswires for training such model

**Comment by eliorc** [comment] 2019-08-01 15:16
Happens to me also, trying to install inside docker also resulted in the same error

```
  ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-wtawfp29/nmslib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-60emi_hb --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_ext
  creating tmp
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.6m -c /tmp/tmpjatnwgsk.cpp -o tmp/tmpjatnwgsk.o -std=c++14
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.6m -c /tmp/tmpjo6vs9_6.cpp -o tmp/tmpjo6vs9_6.o -fvisibility=hidden
  building 'nmslib' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/nmslib
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/space
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/method
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I./nmslib/similarity_search/include -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -I/tmp/pip-install-wtawfp29/nmslib/.eggs/numpy-1.17.0-py3.6-linux-x86_64.egg/numpy/core/include -I/usr/local/include/python3.6m -c nmslib.cc -o build/temp.linux-x86_64-3.6/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO="1.8.1" -std=c++14 -fvisibility=hidden
  nmslib.cc:16:10: fatal error: pybind11/pybind11.h: No such file or directory
   #include <pybind11/pybind11.h>
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for nmslib

```

**Comment by DeNeutoy** [comment] 2019-08-03 22:28
@searchivarius, I wonder if you have any ideas about this issue with the nmslib install? It looks like the pybind dependency for the bindings is not getting installed before the extension is built... 

https://github.com/nmslib/nmslib/blob/master/python_bindings/setup.py#L43

**Comment by searchivarius** [comment] 2019-08-04 16:11
Hi @DeNeutoy I am a bit lost here. Which part of the nmslib installation doesn't work and it's supposed to be working? Thank you!

**Comment by DeNeutoy** [comment] 2019-08-05 02:46
Sorry - perhaps a bit premature to ask you as i'm not sure under exactly what conditions the error that @eliorc reported above occurs.

@eliorc you said you'd reproduced that error in a Dockerfile - could you share a minimal failure, so we can figure out why the nmslib build is failing the first time? This may not be a bug (e.g it may require the `python3-dev` headers or something), but several people have come across this install failure now and it would be nice to be able to raise a better warning or common fixes etc.

**Comment by eliorc** [comment] 2019-08-05 07:07
@DeNeutoy I'll try to do so and update here

**Comment by eliorc** [comment] 2019-08-08 09:02
Ok, I've reproduced this outside of the Docker too, the following requirements file reproduces this, on an Ubuntu 18.04, Python 3.6.8, pip 19.2.1 - It fails at first to install `nmslib`, and then succeeds when retrying in the end.

requirements.txt, this is the original one, obviously I'm sure removing some libs will stil lcause the error:

```bash
networkx
dvc
obonet
xlrd
pandas
scipy
numpy
matplotlib
seaborn
tqdm
gensim
spacy
scispacy==0.2.2
nltk
tensorflow-gpu==2.0.0-beta1
pymongo
sacred
gitpython
```

**Comment by danielkingai2** [comment] 2019-08-09 21:21
I'm not sure that this is actually an issue. I've had the same behavior (`error: command 'gcc' failed with exit status 1` gets output along the way, but installation eventually succeeds), and haven't had any issues actually using `nmslib`. Maybe we just add `numpy` as a dependency in `setup.py` to address @lfoppiano's original problem and don't worry about that `gcc` failure along the way.

**Comment by SaulAryehKohn** [comment] 2019-08-12 14:29
The installation failed for me also (i.e. scispacy did not eventually install) due to the same error with nmslib @lfoppiano lists above. His fix, downloading nmslib separately using the `akode` conda channel worked, and I was able to use `pip install scispacy --no-deps` to install scispacy afterwards.

**Comment by DeNeutoy** [comment] 2019-08-12 17:01
FYI I merged a pin for pybind into nmslib, which should hopefully fix some of these issues: https://github.com/nmslib/nmslib/pull/405

Because pybind is a common library, it is frequently already installed, so unless a library specifically pins it, it won't be updated. In particular, there was an issue with pypi's ability to find pybind C headers which are needed for building C/C++ extensions, which they have now apparently fixed in a newer version of pybind than what nmslib were using. So once nmslib release a new version, we can pin to that and see if it helps.

**Comment by adityajo** [comment] 2019-08-15 06:36
pip install failed for me as well. 

It also screwed up with my conda installation - thanks to the conda configuration that the tutorial wants me to create. Now, tensorflow/sklearn .. none of these libraries can be imported on my python.

Disappointed.

**Comment by DeNeutoy** [comment] 2019-08-15 07:40
@adityajo - installing conda will add the conda root environment to your PATH or PYTHONPATH environment variables, which dictate where your OS looks to find the version of python to run. This is probably what happened, and should be easily fixable by:

1) Removing your conda installation
or 
2) Removing anything involving `anaconda` or `miniconda` from your python path.

**Comment by ehobbs2** [comment] 2019-08-31 17:28
I also have the same problem installing with regard to nmslib. Unfortunately, conda install -c akode nmslib fails with the package not being available from current channels. I see it on Anaconda cloud, so don't know what channel it wants. I am on Windows 10, so perhaps it is unavailable for that. I was wondering if there were another way to get the nmslib package.

**Comment by mrxiaohe** [comment] 2019-08-31 17:41
@ehobbs2 Clone the `nmslib` repository first. Once you have that, go into the `python_bindings` folder, and do `python setup.py install` in your Windows cmd prompt. You may need admin privilege to install correctly (Open the cmd prompt with administrator status).

**Comment by ehobbs2** [comment] 2019-08-31 18:09
Thanks very much for the suggestion. I see that this builds from source, but at the moment I don't have a C++ compiler installed. I'll have to download that and try again.

**Comment by danielkingai2** [comment] 2019-09-01 23:06
I think I was able to replicate the issue by trying to install with `python setup.py install`. What worked for me in this scenario is to install `pybind11` with `pip install pybind11` before trying to install `scispacy`. Could you try this and see if it works for you?

**Comment by ehobbs2** [comment] 2019-09-02 19:37
Thanks for suggesting this; however, unfortunately, it didn't take care of the problem. In my case, it looks like pybind11 was installed since when I went to install it, I got "Requirement is already satisfied: pybind11 in C:\...\anaconda3\lib\site-packages (2.3.0)." Running pip install scispacy after this results in the original problem with nmslib. It wants to built the library from source, and I still haven't downloaded a C++ compiler yet (this being a holiday weekend). The process is set up to build the wheel for this library, so it would probably complete OK if the compiler were there.

**Comment by danielkingai2** [comment] 2019-09-03 16:40
Is `pybind11` installed in your base environment or in your active environment? i.e. what is the `...` of the path you provided?

**Comment by ehobbs2** [comment] 2019-09-03 23:41
The path is C:\users\myname. This is in the base environment, which is the active one.

**Comment by danielkingai2** [comment] 2019-09-03 23:47
Ah, not sure if this will make a difference or not, but I would suggest going through the whole installation procedure in a new conda environment, rather in your base environment

**Comment by ehobbs2** [comment] 2019-09-03 23:55
I tried doing that, creating a separate environment. However, I'm not very knowledgeable about Anaconda, and when I went to do pip install in the scispacy environment following the installation instructions, it told me it couldn't find pip. I was interested in giving scispacy a quick test to see what it extracted from some documents I have, so just reverted to using the base environment.

**Comment by sudarshan85** [comment] 2019-09-14 20:28
I'm having the same issue.

> FYI from the next release, you should just be able to pip install only the models and just use spacy to load them, without having to even install scispacy

Is there an ETA on this?

**Comment by danielkingai2** [comment] 2019-09-17 19:58
@sudarshan85 This should be the case for the current version (0.2.3)

**Comment by danielkingai2** [comment] 2019-09-17 20:20
Is anyone on this thread able to share a dockerfile that reproduces the failed installation? (Not the installation that fails the first time but eventually succeeds)

**Comment by ghostintheshellarise** [comment] 2019-10-27 10:13
I guess it has to do with python version

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - nmslib -> python[version='>=3.6,<3.7.0a0']

Your python: python=3.7

But i cannot choose the 3.6 version to install when i am using anaconda installer to manage the installation.

**Comment by danielkingai2** [comment] 2019-10-28 17:15
You can create a conda environment with python 3.6 like so `conda create -n myenv python=3.6`. See more about working with conda environments here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by danielkingai2** [comment] 2019-11-06 22:14
I think this issue might have been resolved now that nmslib provides wheels? Could someone who was having trouble installing before try again in a clean environment? Otherwise we might able to close this issue @DeNeutoy

**Comment by searchivarius** [comment] 2019-11-07 01:33
Hi @danielkingai2 and all, I am actually, creating another build this evening. I appreciate if you could test the outcome tomorrow. Yes, now NMSLIB does provide binary wheels. Build from sources should be easier now too, as we require a more recent version of pybind11. 

Thank you!

**Comment by danielkingai2** [comment] 2019-11-08 17:56
@searchivarius What did you want us to try? Just normal pip install?

**Comment by searchivarius** [comment] 2019-11-08 18:21
@danielkingai2 yes, and how using precompiled binaries affects efficiency. Thank you!

**Comment by danielkingai2** [comment] 2019-11-08 18:38
@searchivarius everything went smoothly, both install from binary and install from source. Don't have any formal tests for efficiency, but no noticeable difference between the two for our use case. Thanks!

**Comment by danielkingai2** [comment] 2019-11-08 18:39
Closing this issue as I believe it has been resolved by the latest updates to `nmslib`. If you still have issues, feel free to reopen it!

**Closed by danielkingai2** 2019-11-08 18:39 UTC

**Comment by searchivarius** [comment] 2019-11-08 18:44
@danielkingai2 very nice, many thanks!
