### ISSUE TITLE
How is concept_aliases.json constructed?

### ISSUE THREAD

**Issue by izuna385** [allenai/scispacy#191] opened 2020-01-29 06:24 UTC
How `concept_aliases.json` is constructed?
https://github.com/allenai/scispacy/search?q="concept_aliases"&unscoped_q="concept_aliases"

By using this table, I think, if mention is included in this table, mention-entity prior(=similarity) is fixed to 1.0. (If my understanding is incorrect, I'd appreciate if you'd write.)

Currently I'm curious about, how this `concept_aliases.json` is constructed?
It seems that this is actually list, whose length is 4426690, but I can't understand how this list was constructed.
Also, I supposed that alias table is something like,
```
{'entitiy1':[alias1_1,alias1_2,alias1_3], 'entity2':[alias2_1,alias2_2,...],...}
```
but `concept_aliases.json` is list. I'd like to know what this list means.

Still I'm currently reading codes and maybe I missed some codes, which is related to constructing this table.

**Comment by DeNeutoy** [comment] 2020-02-04 17:14
Hi @izuna385, sorry this is a little complicated: 


The concept_aliases list is created here. It is all of the possible alias names for all entities.
https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L314

Later on, when it is used, we do ann lookup in "alias space", and then return all canonical entities that have this alias.

https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L253

The reason we do it in this slightly backward way (matching aliases, and then finding entities which have them as an alias) is explained in this comment here:

https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L94

Hopefully that helps! Let me know if you have any questions. Certainly I think the alias list is inefficient in some way, but it works for now :)

**Comment by izuna385** [comment] 2020-02-07 02:14
Thanks for detailed descriptions. seems like avoiding fixed candidates for mentions which might have same alias. (For top1 candidates per mentions which may have many entities in alias table, we have to choose randomly from them, because only clues we have are string and alias table.)

**Comment by DeNeutoy** [comment] 2020-02-07 17:55
Basically, the problem is that if you have some canonical entities like:

```
"Ford County, Texas": ["Ford County", "Ford County, Texas"]
"Ford County, Alabama": ["Ford County", "Ford County, Alabama"]

etc
```
And you encounter the string "Ford County" in some text, there is no way to know which canonical entity (which all share the same alias which is an exact match) you should link to. So we default to returning all of them. Obviously this is the point at which Entity Linking becomes difficult and actually interesting, but the good thing is that this doesn't happen hugely often 😄

**Comment by izuna385** [comment] 2020-02-09 07:58
Actually why I ask this question is, to check the surface-based candidate generation performance.
Is there any report for top-K recall of MedMentions or st21pv dev/test when mention's span are given? (Currently, my interesting is only candidate generation when mention-span is given, and mention detectio is not included.)

This [link](https://github.com/allenai/scispacy/issues/134#issuecomment-510358152)'s "Soft Matching" meets this situation?

**Comment by izuna385** [comment] 2020-02-10 10:19
I personally used candidate_generator.py and checked recall with MedMentions dev sets, under local model. Apologies for my continuous comments, and this issue can be closed.

```
baseline: top1 string is gold acc 49.393338058114814 %
baseline: top1 string is gold acc normalized 61.25329583406574 %

dev data crosswiki top  10 recall 69.579 %
dev data crosswiki top  25 recall 72.439 %
dev data crosswiki top  50 recall 74.102 %
dev data crosswiki top  75 recall 74.846 %
dev data crosswiki top 100 recall 75.433 %
```

**Comment by DeNeutoy** [comment] 2020-02-10 16:10
Yes, this is similar to what we found. However, note that it depends a lot on the quality of the knowledge base - UMLS is quite noisy, which means that very often, a reasonable alternative entity is suggested, even though it is not "correct".

Also, when focusing on performance for the entity linker, you might want to consider increasing this parameter: https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L47

Here is a picture of our results for candidate generation using Gold Mentions on the med mentions dev data:

<img width="405" alt="Screen Shot 2020-02-10 at 8 08 07 AM" src="https://user-images.githubusercontent.com/16001974/74167115-9c932a00-4bdc-11ea-91bf-b3f0a30a2dda.png">

**Comment by izuna385** [comment] 2020-02-11 05:35
Thanks for detailed reports. I'll try and re-check parameters of candidate_generator in my own.

**Comment by DeNeutoy** [comment] 2020-02-17 17:43
Closing, please open more issues if you need any clarifications, or you want to collaborate or something!

**Closed by DeNeutoy** 2020-02-17 17:43 UTC
